### ISSUE TITLE
bash: pip: command not found Issue

### ISSUE THREAD

**Issue by JagBone** [nopeAnon/Automated-HoloCure-Fishing#39] opened 2023-09-11 22:35 UTC
Hi, I followed the video tutorial you have placed in the drive but I'm getting bash: pip: command not found error whenever I try to initiate the line. Anyway to solve this? I've already installed Python.

**Comment by nopeAnon** [comment] 2023-09-12 02:01
Duplicate of  #11

**Closed as completed by nopeAnon** 2023-09-12 02:01 UTC
